import psycopg2
from psycopg2 import Error
from private.data import db_login


def connect_to_database():
